server:
   port: 9096
   
spring: 
  application: 
    name: CONFIG-SERVER
  cloud: 
    config: 
      server:
        git:
          uri: https://gitlab.com/A2Code/config-server.git
          clone-on-start: true      

